/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.clothing.store.manager.view;

import com.mycompany.clothing.store.manager.configuration.exception.RoupaJaExistenteException;
import com.mycompany.clothing.store.manager.configuration.exception.RoupaNaoExistenteException;
import com.mycompany.clothing.store.manager.controller.ClothingController;
import com.mycompany.clothing.store.manager.domain.Shirt;
import com.mycompany.clothing.store.manager.domain.dto.ClothingResponseDTO;
import com.mycompany.clothing.store.manager.domain.dto.ShirtRequestDTO;
import com.mycompany.clothing.store.manager.domain.dto.ShirtResponseDTO;
import com.mycompany.clothing.store.manager.domain.enums.ClothingType;
import com.mycompany.clothing.store.manager.domain.enums.Gender;
import com.mycompany.clothing.store.manager.domain.enums.ShirtSize;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author moise
 */
public class MainWindow extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();

        getContentPane().setLayout(new CardLayout());

        getContentPane().add(PainelPrincipal, "PainelPrincipal");
        getContentPane().add(PainelAdicionar, "PainelAdicionar");
        getContentPane().add(PainelConsultar, "PainelConsultar");
        getContentPane().add(PainelRoupaNormal, "PainelRoupaNormal");
        getContentPane().add(PainelCamisa, "PainelCamisa");
        getContentPane().add(PainelConsultarCamisa, "PainelConsultarCamisa");
        getContentPane().add(PainelTabela, "PainelTabela");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        jButtonAdicionar = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        PainelAdicionar = new javax.swing.JPanel();
        jButtonRoupaNormal = new javax.swing.JButton();
        PainelRoupaNormal = new javax.swing.JPanel();
        jButtonCamisa = new javax.swing.JButton();
        PainelCamisa = new javax.swing.JPanel();
        jTextFieldColor = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jTextFieldQuantity = new javax.swing.JTextField();
        jTextFieldFabric = new javax.swing.JTextField();
        jTextFieldPattern = new javax.swing.JTextField();
        jTextFieldPocket = new javax.swing.JTextField();
        jTextFieldBrand = new javax.swing.JTextField();
        jTextFieldGender = new javax.swing.JTextField();
        jTextFieldStyle = new javax.swing.JTextField();
        jTextFieldClosureType = new javax.swing.JTextField();
        jLabelCor = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabelQuantity = new javax.swing.JLabel();
        jLabelFabric = new javax.swing.JLabel();
        jLabelBrand = new javax.swing.JLabel();
        jLabelStyle = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabelPattern = new javax.swing.JLabel();
        jLabelPocket = new javax.swing.JLabel();
        jLabelClosureType = new javax.swing.JLabel();
        jButtonFinalizar = new javax.swing.JButton();
        jLabelSize = new javax.swing.JLabel();
        jTextFieldSize = new javax.swing.JTextField();
        jCheckBoxCollar = new javax.swing.JCheckBox();
        jCheckBoxSleeve = new javax.swing.JCheckBox();
        PainelConsultar = new javax.swing.JPanel();
        jButtonConsultarCamisa = new javax.swing.JButton();
        PainelConsultarCamisa = new javax.swing.JPanel();
        jLabelPrice1 = new javax.swing.JLabel();
        jLabelQuantity1 = new javax.swing.JLabel();
        jLabelFabric1 = new javax.swing.JLabel();
        jLabelBrand1 = new javax.swing.JLabel();
        jLabelStyle1 = new javax.swing.JLabel();
        jLabelGender1 = new javax.swing.JLabel();
        jLabelPattern1 = new javax.swing.JLabel();
        jLabelPocket1 = new javax.swing.JLabel();
        jLabelClosureType1 = new javax.swing.JLabel();
        jLabelSize1 = new javax.swing.JLabel();
        jTextFieldColor1 = new javax.swing.JTextField();
        jTextFieldSize1 = new javax.swing.JTextField();
        jTextFieldPrice1 = new javax.swing.JTextField();
        jCheckBoxCollar1 = new javax.swing.JCheckBox();
        jTextFieldQuantity1 = new javax.swing.JTextField();
        jCheckBoxSleeve1 = new javax.swing.JCheckBox();
        jTextFieldFabric1 = new javax.swing.JTextField();
        jTextFieldPattern1 = new javax.swing.JTextField();
        jTextFieldPocket1 = new javax.swing.JTextField();
        jTextFieldBrand1 = new javax.swing.JTextField();
        jTextFieldGender1 = new javax.swing.JTextField();
        jTextFieldStyle1 = new javax.swing.JTextField();
        jTextFieldClosureType1 = new javax.swing.JTextField();
        jLabelCor1 = new javax.swing.JLabel();
        jButtonConsultarCamisa1 = new javax.swing.JButton();
        PainelTabela = new javax.swing.JPanel();
        jScrollPaneTabela = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("mainPanel"); // NOI18N

        PainelPrincipal.setName("PainelPrincipal"); // NOI18N

        jButtonAdicionar.setText("ADICIONAR");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jButtonConsultar.setText("CONSULTAR");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jButtonRemover.setText("REMOVER");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelPrincipalLayout = new javax.swing.GroupLayout(PainelPrincipal);
        PainelPrincipal.setLayout(PainelPrincipalLayout);
        PainelPrincipalLayout.setHorizontalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAdicionar)
                    .addComponent(jButtonConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        PainelPrincipalLayout.setVerticalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jButtonAdicionar)
                .addGap(38, 38, 38)
                .addComponent(jButtonConsultar)
                .addGap(40, 40, 40)
                .addComponent(jButtonRemover)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        PainelAdicionar.setName("PainelAdicionar"); // NOI18N

        jButtonRoupaNormal.setText("ROUPA NORMAL");
        jButtonRoupaNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRoupaNormalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelAdicionarLayout = new javax.swing.GroupLayout(PainelAdicionar);
        PainelAdicionar.setLayout(PainelAdicionarLayout);
        PainelAdicionarLayout.setHorizontalGroup(
            PainelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAdicionarLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jButtonRoupaNormal)
                .addContainerGap(526, Short.MAX_VALUE))
        );
        PainelAdicionarLayout.setVerticalGroup(
            PainelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAdicionarLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jButtonRoupaNormal)
                .addContainerGap(522, Short.MAX_VALUE))
        );

        PainelRoupaNormal.setName("PainelRoupaNormal"); // NOI18N

        jButtonCamisa.setText("CAMISA");
        jButtonCamisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCamisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelRoupaNormalLayout = new javax.swing.GroupLayout(PainelRoupaNormal);
        PainelRoupaNormal.setLayout(PainelRoupaNormalLayout);
        PainelRoupaNormalLayout.setHorizontalGroup(
            PainelRoupaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRoupaNormalLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jButtonCamisa)
                .addContainerGap(770, Short.MAX_VALUE))
        );
        PainelRoupaNormalLayout.setVerticalGroup(
            PainelRoupaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRoupaNormalLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButtonCamisa)
                .addContainerGap(524, Short.MAX_VALUE))
        );

        PainelCamisa.setName("PainelCamisa"); // NOI18N

        jLabelCor.setText("COR");

        jLabelPrice.setText("PRECO");

        jLabelQuantity.setText("QUANTIDADE");

        jLabelFabric.setText("TECIDO");

        jLabelBrand.setText("MARCA");

        jLabelStyle.setText("ESTILO");

        jLabelGender.setText("GENERO");

        jLabelPattern.setText("ESTAMPA");

        jLabelPocket.setText("BOLSO");

        jLabelClosureType.setText("TIPO DE FECHAMENTO");

        jButtonFinalizar.setText("FINALIZAR");
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });

        jLabelSize.setText("TAMANHO");

        jCheckBoxCollar.setText("GOLA");
        jCheckBoxCollar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCollarActionPerformed(evt);
            }
        });

        jCheckBoxSleeve.setText("MANGA");
        jCheckBoxSleeve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSleeveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelCamisaLayout = new javax.swing.GroupLayout(PainelCamisa);
        PainelCamisa.setLayout(PainelCamisaLayout);
        PainelCamisaLayout.setHorizontalGroup(
            PainelCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCamisaLayout.createSequentialGroup()
                .addGroup(PainelCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCamisaLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(PainelCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(PainelCamisaLayout.createSequentialGroup()
                                    .addComponent(jLabelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PainelCamisaLayout.createSequentialGroup()
                                    .addComponent(jLabelCor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PainelCamisaLayout.createSequentialGroup()
                                .addComponent(jLabelFabric)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldFabric, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelCamisaLayout.createSequentialGroup()
                                .addComponent(jLabelQuantity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelCamisaLayout.createSequentialGroup()
                                .addComponent(jLabelStyle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelCamisaLayout.createSequentialGroup()
                                .addComponent(jLabelGender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldGender, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelCamisaLayout.createSequentialGroup()
                                .addComponent(jLabelBrand)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelCamisaLayout.createSequentialGroup()
                                .addComponent(jLabelPattern)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPattern, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelCamisaLayout.createSequentialGroup()
                                .addComponent(jLabelPocket)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPocket, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelCamisaLayout.createSequentialGroup()
                                .addComponent(jLabelClosureType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldClosureType, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PainelCamisaLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jButtonFinalizar))
                    .addGroup(PainelCamisaLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(PainelCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxCollar)
                            .addGroup(PainelCamisaLayout.createSequentialGroup()
                                .addComponent(jLabelSize)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSize, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBoxSleeve))))
                .addContainerGap(730, Short.MAX_VALUE))
        );
        PainelCamisaLayout.setVerticalGroup(
            PainelCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCamisaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(PainelCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrice)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuantity)
                    .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFabric)
                    .addComponent(jTextFieldFabric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBrand)
                    .addComponent(jTextFieldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStyle)
                    .addComponent(jTextFieldStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGender)
                    .addComponent(jTextFieldGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPattern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPattern))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPocket)
                    .addComponent(jTextFieldPocket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClosureType)
                    .addComponent(jTextFieldClosureType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSize)
                    .addComponent(jTextFieldSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxCollar)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxSleeve)
                .addGap(88, 88, 88)
                .addComponent(jButtonFinalizar)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        PainelConsultar.setName("PainelConsultar"); // NOI18N

        jButtonConsultarCamisa.setText("CAMISA");
        jButtonConsultarCamisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarCamisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelConsultarLayout = new javax.swing.GroupLayout(PainelConsultar);
        PainelConsultar.setLayout(PainelConsultarLayout);
        PainelConsultarLayout.setHorizontalGroup(
            PainelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultarLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jButtonConsultarCamisa)
                .addContainerGap(944, Short.MAX_VALUE))
        );
        PainelConsultarLayout.setVerticalGroup(
            PainelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultarLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jButtonConsultarCamisa)
                .addContainerGap(487, Short.MAX_VALUE))
        );

        PainelConsultarCamisa.setName("PainelConsultarCamisa"); // NOI18N

        jLabelPrice1.setText("PRECO");

        jLabelQuantity1.setText("QUANTIDADE");

        jLabelFabric1.setText("TECIDO");

        jLabelBrand1.setText("MARCA");

        jLabelStyle1.setText("ESTILO");

        jLabelGender1.setText("GENERO");

        jLabelPattern1.setText("ESTAMPA");

        jLabelPocket1.setText("BOLSO");

        jLabelClosureType1.setText("TIPO DE FECHAMENTO");

        jLabelSize1.setText("TAMANHO");

        jCheckBoxCollar1.setText("GOLA");
        jCheckBoxCollar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCollar1ActionPerformed(evt);
            }
        });

        jCheckBoxSleeve1.setText("MANGA");
        jCheckBoxSleeve1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSleeve1ActionPerformed(evt);
            }
        });

        jLabelCor1.setText("COR");

        jButtonConsultarCamisa1.setText("CONSULTAR CAMISA");
        jButtonConsultarCamisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarCamisa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelConsultarCamisaLayout = new javax.swing.GroupLayout(PainelConsultarCamisa);
        PainelConsultarCamisa.setLayout(PainelConsultarCamisaLayout);
        PainelConsultarCamisaLayout.setHorizontalGroup(
            PainelConsultarCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultarCamisaLayout.createSequentialGroup()
                .addGroup(PainelConsultarCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelConsultarCamisaLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(PainelConsultarCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelConsultarCamisaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(PainelConsultarCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PainelConsultarCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(PainelConsultarCamisaLayout.createSequentialGroup()
                                            .addComponent(jLabelPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(28, 28, 28)
                                            .addComponent(jTextFieldPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PainelConsultarCamisaLayout.createSequentialGroup()
                                            .addComponent(jLabelCor1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(28, 28, 28)
                                            .addComponent(jTextFieldColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PainelConsultarCamisaLayout.createSequentialGroup()
                                        .addComponent(jLabelFabric1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldFabric1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelConsultarCamisaLayout.createSequentialGroup()
                                        .addComponent(jLabelQuantity1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelConsultarCamisaLayout.createSequentialGroup()
                                        .addComponent(jLabelStyle1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldStyle1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelConsultarCamisaLayout.createSequentialGroup()
                                        .addComponent(jLabelGender1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldGender1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelConsultarCamisaLayout.createSequentialGroup()
                                        .addComponent(jLabelBrand1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldBrand1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelConsultarCamisaLayout.createSequentialGroup()
                                        .addComponent(jLabelPattern1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldPattern1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelConsultarCamisaLayout.createSequentialGroup()
                                        .addComponent(jLabelPocket1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldPocket1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelConsultarCamisaLayout.createSequentialGroup()
                                        .addComponent(jLabelClosureType1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldClosureType1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jCheckBoxCollar1)
                            .addGroup(PainelConsultarCamisaLayout.createSequentialGroup()
                                .addComponent(jLabelSize1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSize1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBoxSleeve1)))
                    .addGroup(PainelConsultarCamisaLayout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(jButtonConsultarCamisa1)))
                .addContainerGap(585, Short.MAX_VALUE))
        );
        PainelConsultarCamisaLayout.setVerticalGroup(
            PainelConsultarCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultarCamisaLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(PainelConsultarCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldColor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCor1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelConsultarCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrice1)
                    .addComponent(jTextFieldPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelConsultarCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuantity1)
                    .addComponent(jTextFieldQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelConsultarCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFabric1)
                    .addComponent(jTextFieldFabric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelConsultarCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBrand1)
                    .addComponent(jTextFieldBrand1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelConsultarCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStyle1)
                    .addComponent(jTextFieldStyle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelConsultarCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGender1)
                    .addComponent(jTextFieldGender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelConsultarCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPattern1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPattern1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelConsultarCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPocket1)
                    .addComponent(jTextFieldPocket1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelConsultarCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClosureType1)
                    .addComponent(jTextFieldClosureType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelConsultarCamisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSize1)
                    .addComponent(jTextFieldSize1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxCollar1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxSleeve1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConsultarCamisa1)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        PainelTabela.setName("PainelTabela"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneTabela.setViewportView(jTable1);

        javax.swing.GroupLayout PainelTabelaLayout = new javax.swing.GroupLayout(PainelTabela);
        PainelTabela.setLayout(PainelTabelaLayout);
        PainelTabelaLayout.setHorizontalGroup(
            PainelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTabelaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPaneTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        PainelTabelaLayout.setVerticalGroup(
            PainelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelTabelaLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jScrollPaneTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(649, Short.MAX_VALUE)
                .addComponent(PainelAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(641, 641, 641))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 701, Short.MAX_VALUE)
                    .addComponent(PainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 702, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PainelRoupaNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PainelCamisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PainelConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PainelConsultarCamisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PainelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addComponent(PainelAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(520, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 557, Short.MAX_VALUE)
                    .addComponent(PainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 558, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PainelRoupaNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PainelCamisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PainelConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PainelConsultarCamisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PainelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getAccessibleContext().setAccessibleName("mainPanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        CardLayout a = (CardLayout) getContentPane().getLayout();
        a.show(getContentPane(), "PainelRemover");
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        CardLayout a = (CardLayout) getContentPane().getLayout();
        a.show(getContentPane(), "PainelAdicionar");
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        CardLayout a = (CardLayout) getContentPane().getLayout();
        a.show(getContentPane(), "PainelConsultar");
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonRoupaNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRoupaNormalActionPerformed
        CardLayout a = (CardLayout) getContentPane().getLayout();
        a.show(getContentPane(), "PainelRoupaNormal");
    }//GEN-LAST:event_jButtonRoupaNormalActionPerformed

    private void jButtonCamisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCamisaActionPerformed
        CardLayout a = (CardLayout) getContentPane().getLayout();
        a.show(getContentPane(), "PainelCamisa");
    }//GEN-LAST:event_jButtonCamisaActionPerformed

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
        try {
            finalizarAux();
        } catch (Exception e) {
            handleException(e);
        }
    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    private void jCheckBoxCollarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCollarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxCollarActionPerformed

    private void jCheckBoxSleeveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSleeveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSleeveActionPerformed

    private void jButtonConsultarCamisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarCamisaActionPerformed
        CardLayout a = (CardLayout) getContentPane().getLayout();
        a.show(getContentPane(), "PainelConsultarCamisa");
    }//GEN-LAST:event_jButtonConsultarCamisaActionPerformed

    private void jCheckBoxCollar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCollar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxCollar1ActionPerformed

    private void jCheckBoxSleeve1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSleeve1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSleeve1ActionPerformed

    private void jButtonConsultarCamisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarCamisa1ActionPerformed
        try {
            consultarCamisaAux();
        } catch(RoupaNaoExistenteException e) {
            handleException(e);
        } catch (Exception e) {
            handleException(e);
        }
    }//GEN-LAST:event_jButtonConsultarCamisa1ActionPerformed

    private void finalizarAux() throws Exception {
        Double price = Double.parseDouble(jTextFieldPrice.getText());
        Integer quantity = Integer.parseInt(jTextFieldQuantity.getText());
        Gender gender;
        String fabric = (jTextFieldFabric.getText().isEmpty() || jTextFieldFabric.getText().isBlank()) ? null : jTextFieldFabric.getText();
        String brand = (jTextFieldBrand.getText().isEmpty() || jTextFieldBrand.getText().isBlank()) ? null : jTextFieldBrand.getText();
        String style = (jTextFieldStyle.getText().isEmpty() || jTextFieldStyle.getText().isBlank()) ? null : jTextFieldStyle.getText();
        String pattern = (jTextFieldPattern.getText().isEmpty() || jTextFieldPattern.getText().isBlank()) ? null : jTextFieldPattern.getText();
        Integer pocket = (jTextFieldPocket.getText().isEmpty() || jTextFieldPocket.getText().isBlank()) ? 0 : Integer.parseInt(jTextFieldPocket.getText());
        String closureType = (jTextFieldClosureType.getText().isEmpty() || jTextFieldClosureType.getText().isBlank()) ? null : jTextFieldClosureType.getText();
        gender = Gender.MALE;ShirtSize size;
        
        if (jTextFieldGender.getText().charAt(0) == 'M') {
            gender = Gender.MALE;
        } else if (jTextFieldGender.getText().charAt(0) == 'F') {
            gender = Gender.FEMALE;
        } else {
            throw new IllegalArgumentException("INSIRA DADOS VALIDOS");
        }
        
        if (jTextFieldSize.getText().equals("P")) {
            size = ShirtSize.SMALL;
        } else if (jTextFieldSize.getText().equals("M")) {
            size = ShirtSize.MEDIUM;
        } else if (jTextFieldSize.getText().equals("G")) {
            size = ShirtSize.LARGE;
        } else {
            throw new IllegalArgumentException("INSIRA DADOS VALIDOS");
        }

        ShirtRequestDTO shirtData = new ShirtRequestDTO(jTextFieldColor.getText(), price, quantity, fabric, brand, style, gender, pattern, pocket, closureType,
                ClothingType.STANDARD, jCheckBoxSleeve.isSelected(), jCheckBoxCollar.isSelected(), size);
        ClothingController.register(shirtData);
        JOptionPane.showMessageDialog(this, "ROUPA CADASTRADA", "RESULTADO", JOptionPane.INFORMATION_MESSAGE);
    }

    private void consultarCamisaAux() throws Exception {
        Double price = (jTextFieldPrice1.getText().isEmpty()) ?0D :Double.parseDouble(jTextFieldPrice1.getText());
        Integer pocket = (jTextFieldPocket1.getText().isEmpty()) ?0 :Integer.parseInt(jTextFieldPocket1.getText());
        Integer quantity = (jTextFieldQuantity1.getText().isEmpty()) ?0 :Integer.parseInt(jTextFieldQuantity1.getText());
        Gender gender = null;
        ShirtSize shirtSize = null;
        String color = jTextFieldColor1.getText().trim();
        
        if (jTextFieldSize1.getText().equals("P")) {
            shirtSize = ShirtSize.SMALL;
        } else if (jTextFieldSize1.getText().equals("M")) {
            shirtSize = ShirtSize.MEDIUM;
        } else if (jTextFieldSize1.getText().equals("G")) {
            shirtSize = ShirtSize.LARGE;
        } else if(shirtSize != null){
            throw new IllegalArgumentException("DADOS INVALIDOS");
        }

        if (jTextFieldGender1.getText().equals("M")) {
            gender = Gender.MALE;
        } else if (jTextFieldGender1.getText().equals("F")) {
            gender = Gender.FEMALE;
        } else if(shirtSize != null) {
            throw new IllegalArgumentException("DADOS INVALIDOS");
        }

        ShirtRequestDTO data = new ShirtRequestDTO(color, price, quantity, jTextFieldFabric1.getText(),
                jTextFieldBrand1.getText(), jTextFieldStyle1.getText(), gender, jTextFieldPattern1.getText(),
                pocket, jTextFieldClosureType1.getText(), ClothingType.STANDARD, jCheckBoxSleeve1.isSelected(),
                jCheckBoxCollar1.isSelected(), shirtSize);
        
        
        
        List<ClothingResponseDTO> list = ClothingController.consult(data);
        fillTableShirt(list);
    }

    private void fillTableShirt(List<ClothingResponseDTO> list) {
        DefaultTableModel model = new DefaultTableModel();

        if (list.getFirst() instanceof ShirtResponseDTO) {
            model.addColumn("ID");
            model.addColumn("COLOR");
            model.addColumn("PRICE");
            model.addColumn("QUANTITY");
            model.addColumn("BRAND");
            model.addColumn("SIZE");
            model.addColumn("GENDER");
            model.addColumn("CLOSURE TYPE");
            model.addColumn("CLOTHING TYPE");
            model.addColumn("PATTERN");
            model.addColumn("FABRIC");
            model.addColumn("COLLAR");
            model.addColumn("SLEEVE");
            
            for (ClothingResponseDTO data : list) {
                ShirtResponseDTO shirtData = (ShirtResponseDTO) data;
                model.addRow(new Object[]{
                    shirtData.id(),
                    shirtData.color(),
                    shirtData.price(), 
                    shirtData.quantity(),
                    shirtData.brand(), 
                    shirtData.size(),
                    shirtData.gender(), 
                    shirtData.closureType(),
                    shirtData.clothingType(),
                    shirtData.pattern(),
                    shirtData.fabric(),
                    shirtData.collar(), 
                    shirtData.sleeve()
                });
            }
            jTable1.setModel(model);
            CardLayout a = (CardLayout) getContentPane().getLayout();
            a.show(getContentPane(), "PainelTabela");
        }
    }

    private void handleException(Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "RESULTADO", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelAdicionar;
    private javax.swing.JPanel PainelCamisa;
    private javax.swing.JPanel PainelConsultar;
    private javax.swing.JPanel PainelConsultarCamisa;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JPanel PainelRoupaNormal;
    private javax.swing.JPanel PainelTabela;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonCamisa;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonConsultarCamisa;
    private javax.swing.JButton jButtonConsultarCamisa1;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JButton jButtonRoupaNormal;
    private javax.swing.JCheckBox jCheckBoxCollar;
    private javax.swing.JCheckBox jCheckBoxCollar1;
    private javax.swing.JCheckBox jCheckBoxSleeve;
    private javax.swing.JCheckBox jCheckBoxSleeve1;
    private javax.swing.JLabel jLabelBrand;
    private javax.swing.JLabel jLabelBrand1;
    private javax.swing.JLabel jLabelClosureType;
    private javax.swing.JLabel jLabelClosureType1;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelCor1;
    private javax.swing.JLabel jLabelFabric;
    private javax.swing.JLabel jLabelFabric1;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelGender1;
    private javax.swing.JLabel jLabelPattern;
    private javax.swing.JLabel jLabelPattern1;
    private javax.swing.JLabel jLabelPocket;
    private javax.swing.JLabel jLabelPocket1;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelPrice1;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelQuantity1;
    private javax.swing.JLabel jLabelSize;
    private javax.swing.JLabel jLabelSize1;
    private javax.swing.JLabel jLabelStyle;
    private javax.swing.JLabel jLabelStyle1;
    private javax.swing.JScrollPane jScrollPaneTabela;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBrand;
    private javax.swing.JTextField jTextFieldBrand1;
    private javax.swing.JTextField jTextFieldClosureType;
    private javax.swing.JTextField jTextFieldClosureType1;
    private javax.swing.JTextField jTextFieldColor;
    private javax.swing.JTextField jTextFieldColor1;
    private javax.swing.JTextField jTextFieldFabric;
    private javax.swing.JTextField jTextFieldFabric1;
    private javax.swing.JTextField jTextFieldGender;
    private javax.swing.JTextField jTextFieldGender1;
    private javax.swing.JTextField jTextFieldPattern;
    private javax.swing.JTextField jTextFieldPattern1;
    private javax.swing.JTextField jTextFieldPocket;
    private javax.swing.JTextField jTextFieldPocket1;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldPrice1;
    private javax.swing.JTextField jTextFieldQuantity;
    private javax.swing.JTextField jTextFieldQuantity1;
    private javax.swing.JTextField jTextFieldSize;
    private javax.swing.JTextField jTextFieldSize1;
    private javax.swing.JTextField jTextFieldStyle;
    private javax.swing.JTextField jTextFieldStyle1;
    // End of variables declaration//GEN-END:variables
}
